### ISSUE TITLE
Use config to generate server routes

### ISSUE THREAD

**Issue by zmackie** [danielmiessler/fabric#4]
The idea is that you could use a yml document and autogenerate all of the routes (and probably the client code too)....

The code below is more complicated than necessary so I'll clean it up and make it more concise and submit as a PR. Just wanted to get the idea out there for discussion.

```python
import yaml
from flask import Flask, request, jsonify
from your_authentication_module import auth_required  # Import your authentication module
from your_fetch_module import fetch_content_from_url  # Import your content fetching module
import openai

app = Flask(__name__)

def create_endpoint(endpoint_config):
    @app.route(endpoint_config["path"], methods=endpoint_config.get("methods", ["POST"]))
    @auth_required
    def generic_endpoint():
        data = request.get_json()

        if "input" not in data:
            return jsonify({"error": "Missing input parameter"}), 400

        input_data = data["input"]

        responses = []
        for content_url in endpoint_config["content_urls"]:
            content = fetch_content_from_url(content_url)
            responses.append({"role": "system" if content_url.endswith("system.md") else "user", 
                              "content": content + ("\n" + input_data if content_url.endswith("user.md") else "")})

        try:
            response = openai.chat.completions.create(
                model=endpoint_config.get("model", "gpt-4-1106-preview"),
                messages=responses,
                temperature=endpoint_config.get("temperature", 0.0),
                top_p=endpoint_config.get("top_p", 1),
                frequency_penalty=endpoint_config.get("frequency_penalty", 0.1),
                presence_penalty=endpoint_config.get("presence_penalty", 0.1),
            )
            assistant_message = response.choices[0].message.content
            return jsonify({"response": assistant_message})
        except Exception as e:
            return jsonify({"error": str(e)}), 500

    return generic_endpoint

# Load the config file
with open("config.yml", "r") as file:
    config = yaml.safe_load(file)

# Create endpoints based on the config
for endpoint_name, endpoint_config in config.items():
    create_endpoint(endpoint_config)

if __name__ == "__main__":
    app.run(debug=True)
```

```yml
extwis:
  path: "/extwis"
  methods: ["POST"]
  content_urls:
    - "https://raw.githubusercontent.com/danielmiessler/fabric/main/patterns/extract_wisdom/system.md"
    - "https://raw.githubusercontent.com/danielmiessler/fabric/main/patterns/extract_wisdom/user.md"
  model: "gpt-4-1106-preview"
  temperature: 0.0
  top_p: 1
  frequency_penalty: 0.1
  presence_penalty: 0.1
# More endpoints can be defined similarly
```
